"""
Reports center: list, fetch, download, and regenerate PDF dossiers.

A PDF dossier is a rendered view of a frozen investigation. It is not
regenerated on read — a report that changes every time you open it is not a
record of anything. `POST /{id}/regenerate` exists as an explicit, labelled
action so the operator knows it is producing a *new* document from stored
data, not editing the old one.
"""

from __future__ import annotations

import os
import re
from typing import Optional

from fastapi import APIRouter, Depends, Header, HTTPException, Query, status
from fastapi.responses import FileResponse

import config
from models.api import ErrorResponse, PaginatedResponse
from routers.trace import _identity
from services.report_service import render_trace_report
from services.repository import get_repository

router = APIRouter(prefix="/reports", tags=["reports"])

#: Filenames are generated by `report_filename_for`, but the static mount also
#: serves whatever is in the report directory, so a path traversal check stays.
_SAFE_NAME = re.compile(r"^[A-Za-z0-9_.-]+\.pdf$")


def _not_found(what: str) -> HTTPException:
    return HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail={
            "error": "not_found",
            "detail": f"No {what} is available to you.",
            "kind": "not_found",
        },
    )


def _resolve(filename: str) -> str:
    """Map a report filename to a path on disk, refusing anything else."""
    if not _SAFE_NAME.match(filename or ""):
        # 400, not 404: the request is malformed rather than absent.
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={
                "error": "invalid_report_name",
                "detail": "A report name is a generated .pdf filename.",
                "kind": "invalid_input",
            },
        )
    path = os.path.abspath(os.path.join(config.REPORT_DIR, filename))
    if not path.startswith(os.path.abspath(config.REPORT_DIR) + os.sep):
        raise _not_found("report")
    return path


@router.get(
    "",
    response_model=PaginatedResponse,
    responses={401: {"model": ErrorResponse}},
    summary="List generated reports for this user",
)
def list_reports(
    limit: int = Query(25, ge=1, le=200),
    offset: int = Query(0, ge=0),
    chain: Optional[str] = None,
    authorization: Optional[str] = Header(None),
    identity: dict = Depends(_identity),
) -> PaginatedResponse:
    """
    Reports are a view over saved investigations, not a separate store — a
    report exists because an investigation produced it. The list is scoped to
    the caller.
    """
    rows, total = get_repository().list_investigations(
        identity.get("user_id"), limit=limit, offset=offset, chain=chain,
    )
    items = [
        {
            "investigation_id": r.get("id"),
            "title": r.get("title") or r.get("seed"),
            "chain": r.get("chain"),
            "chain_name": r.get("chain_name"),
            "seed": r.get("seed"),
            "risk_level": r.get("risk_level"),
            "risk_score": r.get("risk_score"),
            "created_at": r.get("created_at"),
            "has_report": bool(r.get("has_report")),
            "report_url": r.get("report_url"),
        }
        for r in rows
        if r.get("has_report")
    ]
    return PaginatedResponse(items=items, total=total, limit=limit, offset=offset)


@router.get(
    "/{filename}",
    responses={401: {"model": ErrorResponse}, 404: {"model": ErrorResponse}},
    summary="Download a generated PDF dossier",
)
def download_report(
    filename: str,
    authorization: Optional[str] = Header(None),
    identity: dict = Depends(_identity),
) -> FileResponse:
    """
    Serve the PDF by name.

    In a multi-user deployment the file is also checked against the caller's
    own investigations, so a filename guessed from the pattern cannot be used
    to read another analyst's dossier. In demo mode (no `user_id` isolation)
    the existence check is skipped and the directory is single-user anyway.
    """
    path = _resolve(filename)
    if not os.path.isfile(path):
        raise _not_found("report")
    if identity.get("state") == "authenticated":
        owned = False
        rows, _ = get_repository().list_investigations(
            identity.get("user_id"), limit=1000, offset=0,
        )
        for row in rows:
            if (row.get("report_url") or "").endswith(filename):
                owned = True
                break
        if not owned:
            raise _not_found("report")
    return FileResponse(
        path,
        media_type="application/pdf",
        filename=filename,
    )


@router.post(
    "/{investigation_id}/regenerate",
    responses={401: {"model": ErrorResponse}, 404: {"model": ErrorResponse}},
    summary="Re-render a PDF from a stored investigation",
)
def regenerate_report(
    investigation_id: str,
    authorization: Optional[str] = Header(None),
    identity: dict = Depends(_identity),
) -> dict:
    """
    Produce a fresh PDF from the *stored* result — not by re-querying providers.

    This deliberately does not re-trace. Re-tracing would return a different
    graph describing a different moment, attached to the same investigation id,
    which is exactly the kind of silent mutation a forensic record must not
    have. If the investigator wants current chain data, they run a new trace.
    """
    row = get_repository().get_investigation(investigation_id, identity.get("user_id"))
    if row is None:
        raise _not_found("investigation")
    result = row.get("result") or {}
    if not result:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={
                "error": "no_stored_result",
                "detail": "This investigation has no stored result to render.",
                "kind": "invalid_input",
            },
        )

    from services.report_service import report_filename_for
    from services.trace_orchestrator import TraceResult

    try:
        trace = TraceResult.from_dict(result)
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={
                "error": "unstorable_result",
                "detail": (
                    "The stored result could not be read back as a TraceResult "
                    f"({type(exc).__name__}). It may have been written by an "
                    "older schema."
                ),
                "kind": "invalid_input",
            },
        )

    filename = report_filename_for(
        result.get("chain", "unknown"),
        result.get("seed", "unknown"),
        investigation_id,
    )
    os.makedirs(config.REPORT_DIR, exist_ok=True)
    path = os.path.join(config.REPORT_DIR, filename)
    try:
        render_trace_report(trace, path, investigator=identity.get("email"))
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "error": "report_render_failed",
                "detail": f"The PDF could not be rendered ({type(exc).__name__}).",
                "kind": "internal",
            },
        ) from exc

    url = f"/reports/{filename}"
    get_repository().record_report(investigation_id, identity.get("user_id"), url)
    return {
        "investigation_id": investigation_id,
        "report_url": url,
        "note": (
            "Re-rendered from the stored result. Chain state may have changed "
            "since this investigation was first run; the stored data is "
            "unchanged."
        ),
    }
